### ISSUE TITLE
UX/UI > Colours

### ISSUE THREAD

**Issue by rhiannb** [Kyle-Scudder/the-date-pot#59]
- [x] buttons throughout that are currently plurple to be ff6f61
- [x] hover colour to be ff9a90
- [x] delete/warning to be BE3455
- [x] add button/success B2AC88
- [ ] all text/icons on buttons to be white
- [x] background colour dark mode to be 151711
- [x] background colour light mode to be f1f2ee
- [x] offset background; dark mode to be 2a2e23
- [x] offset background; light mode to be e5e7e1
- [x] pill colour; dark mode to be e5e7e1
- [x] pill colour; light mode to be 2a2e23
- [ ] in drink pots; stars to be FDFD96
- [ ] Seach bars.  When not clicked on, white outline. When within the box to be the primary colour ff6f61

**Comment by kylescudder** [comment]
Find new colours for:

- Add button/success
- delete/warning
- Rating/Notes card delete button to also use danger colour
-  offset background; light mode

**Comment by rhiannb** [comment]
Light mode colours; 
- delete/danger 
- add/success 
- pill colour
